version: '3'

services:
  web:
    build:
      context: .
      dockerfile: confs/local/Dockerfile
    ports:
      - '8000:8000'
    command: python main.py
    expose:
      - 8000

    volumes:
        - .:/usr/src/app/staticfiles
    
